---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "Debian" or
      ansible_os_family == "RedHat"

- name: Install NTP
  package:
    name: "{{ ntp_pkg }}"
    state: present
  notify:
    - Restart NTP service
  tags:
    - ntp_pkg

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: "{{ ntp_conf_file }}"
  register: ntp_config_result
  notify:
    - Restart NTP service
  tags:
    - ntp_config

- name: Make sure NTP service is enabled
  service:
    name: "{{ ntp_service }}"
    enabled: true

- name: Make sure NTP service is running
  service:
    name: "{{ ntp_service }}"
    enabled: true
    state: running
  register: ntp_service_started
  when: >
      not ntp_config_result.changed
