---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "Debian" or
      ansible_os_family == "RedHat"
  tags:
    - ntp_assert

- name: Install NTP
  package:
    name: "{{ ntp_pkg }}"
  notify:
    - Restart NTP service
  tags:
    - ntp_pkg

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: "{{ ntp_conf_file }}"
  notify:
    - Restart NTP service
  tags:
    - ntp_config

- name: Enable NTP service
  service:
    name: "{{ ntp_service }}"
    enabled: true
  tags:
    - ntp_service

- name: Start NTP service
  service:
    name: "{{ ntp_service }}"
    state: running
  register: ntp_service_started
  tags:
    - ntp_service
